image: dockerproxy-iva.si.francetelecom.fr/node:latest

services:
  - dockerproxy-iva.si.francetelecom.fr/mongo:latest
  


test:
  stage: test
  tags: 
    - docker
    - devopsstore
    - docker-privileged
    - devwatt
    - shared
    - rsc

  script:
    - npm start
    - wget http://localhost:3000
    