image: dockerproxy-iva.si.francetelecom.fr/node:latest

services:
  - name: dockerproxy-iva.si.francetelecom.fr/mongo:latest
    alias: mongo
  
stages:
  - restore
  - test

restore:
  stage: restore
  image: dockerproxy-iva.si.francetelecom.fr/mongo:latest
  tags: 
    - docker
    - devopsstore
    - docker-privileged
    - devwatt
    - shared
    - rsc

  script:
    - mongorestore --host mongo:27017 --db "ApiAxiomeDB" --drop --collection "documents" "./ApiAxiomeDB/documents.bson"
    - mongorestore --host mongo:27017 --db "ApiAxiomeDB" --drop --collection "rankings" "./ApiAxiomeDB/rankings.bson"

    