image: dockerproxy-iva.si.francetelecom.fr/node:latest

services:
  - name: dockerproxy-iva.si.francetelecom.fr/mongo:latest
    alias: mongo
  


test:
  stage: test
  tags: 
    - docker
    - devopsstore
    - docker-privileged
    - devwatt
    - shared
    - rsc

  script:
    - npm install -g forever
    - foreter start server.js
    - wget localhost:3000

    