image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags: 
    - docker
    - rsc
    - shared

  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
